name: 'cassler ci'
on:
  push:
  pull_request:
    types: [ opened, reopened ]
jobs:
  unit-test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:

      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - uses: actions/checkout@v1

      - name: Install dependencies
        run: go get -u 

      - name: Test
        run: go test -v

  build-docker-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.15.x'

      - uses: actions/checkout@v1
      
      - name: Docker Build
        run: docker build -t cassler:latest .

      - name: Docker Tag
        run: docker tag cassler:latest fidelissauro/cassler:latest

      - name: Docker Login
        run: echo '${DOCKER_PASSWORD}' | docker login -u '${DOCKER_USERNAME}' --password-stdin

      - name: Docker Push
        run: docker push fidelissauro/cassler:latest

      